version: '3'

services:
  db:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "5432:5432"
    env_file:
      - test_vars.env
  web:
    build: .
    env_file:
      - test_vars.env
    command: dockerize -wait tcp://db:5432 python trip_app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"